version: '3'
services:
  website:
    build: .
    image: mixnjuice/website:latest
    container_name: mixnjuice-website
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
networks:
  default:
    external:
      name: proxy_proxy
