version: 2.1

orbs:
  mattermost-notify: bulletlogic/mattermost-notify@0.0.4

commands:
  prepare:
    description: Install dependencies
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

jobs:
  build:
    working_directory: ~/mixnjuice-website
    docker:
      - image: circleci/node:latest
    steps:
      - prepare
      - run:
          name: test
          command: npm test
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - prepare
      - add_ssh_keys:
          fingerprints:
            - 'ba:0b:ef:da:ca:3b:a0:b2:05:da:ca:b6:7a:53:ef:89'
      - run:
          name: build
          command: npm run build
      - run:
          name: deploy
          command: npm run deploy
  notify_success:
    docker:
      - image: byrnedo/alpine-curl:latest
    steps:
      - mattermost-notify/notify_on_success:
          webhook: '$MATTERMOST_WEBHOOK_WEBSITE'
  notify_failure:
    docker:
      - image: byrnedo/alpine-curl:latest
    steps:
      - mattermost-notify/notify_on_failure:
          webhook: '$MATTERMOST_WEBHOOK_WEBSITE'

workflows:
  version: 2
  main_workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - notify_success:
          context: webhooks
          requires:
            - build
      - notify_failure:
          context: webhooks
