version: 2.1

orbs:
  mattermost-notify: bulletlogic/mattermost-notify@0.0.4

jobs:
  build:
    working_directory: ~/gusta-website
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
  notify_success:
    docker:
      - image: byrnedo/alpine-curl:latest
    steps:
      - mattermost-notify/notify_on_success:
          webhook: '$MATTERMOST_WEBHOOK_WEBSITE'
  notify_failure:
    docker:
      - image: byrnedo/alpine-curl:latest
    steps:
      - mattermost-notify/notify_on_failure:
          webhook: '$MATTERMOST_WEBHOOK_WEBSITE'

workflows:
  version: 2
  main_workflow:
    jobs:
      - build
      - notify_success:
          context: webhooks
          requires:
            - build
      - notify_failure:
          context: webhooks
